version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ict4bd:latest
    container_name: ict4bd
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Rome
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
